id: AA06FF7E6
title: f265F
type: translation
source_metadata:
  languages:
  - sa
  - pi
  - pgd
  datatype: PlainText
  created_at: 2022-05-27 15:07:15.058936
  last_modified_at: 2022-05-27 15:07:15.058944
